language: python

matrix:
  include:
  - name: "Python 3.6 Unit Test"
    python: "3.6"
    env: PYSTAN_VERSION="latest" NAME="PY36MAJOR"
  - name: "Python 3.5 Unit Test"
    python: "3.5"
    env: PYSTAN_VERSION="latest" NAME="PY35MAJOR"
  - name: "PyStan preview Unit Test"
    python: "3.6"
    env: PYSTAN_VERSION="preview" NAME="PY36MINOR"

addons:
  apt_packages:
    - pandoc

cache:
  directories:
    - $HOME/.theano
    - $HOME/miniconda

install:
  - sudo apt-get update
  - . ./scripts/install_miniconda.sh
  - conda info -a
  - . ./scripts/create_testenv.sh
  - pip install coveralls

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- export MKL_THREADING_LAYER=GNU

script:
  - if [[ $NAME == "PY36MAJOR" ]]; then . ./scripts/lint.sh ; fi
  - pytest -v arviz/tests/ --cov=arviz/
  - if [[ $NAME == "PY36MAJOR" ]]; then travis-sphinx build --nowarn --source=doc ; fi

after_success:
  - if [[ $NAME == "PY36MAJOR" ]]; then travis-sphinx deploy; fi
  - coveralls
